#define MCryptVer "2.5.8" 
/*  */
#define PACKAGE_VERSION_STRING MCryptVer
#define PACKAGE_VERSION_MAJOR 2
#define PACKAGE_VERSION_MINOR 2
#define PACKAGE_VERSION_PATCH 8
#define PACKAGE_VERSION_SUBMINOR 0
