#!/bin/sh

# Build zipfiles for GLib on Win32: Separate runtime and developer ones.
# After running make install, run this.

ZIP=/tmp/glib-2.0.7.zip
DEVZIP=/tmp/glib-dev-2.0.7.zip

cd /usr

rm $ZIP
zip -r $ZIP -@ <<EOF
COPYING.LIB-2
bin/gspawn-win32-helper.exe
lib/libglib-2.0-0.dll
lib/libgmodule-2.0-0.dll
lib/libgobject-2.0-0.dll
lib/libgthread-2.0-0.dll
EOF

zip -r $ZIP lib/locale/*/LC_MESSAGES/glib20.mo

rm $DEVZIP
zip -r $DEVZIP -@ <<EOF
bin/glib-genmarshal.exe
bin/glib-gettextize
bin/glib-mkenums
bin/gobject-query.exe
include/glib-2.0
lib/libglib-2.0.dll.a
lib/glib-2.0.lib
lib/libgmodule-2.0.dll.a
lib/gmodule-2.0.lib
lib/libgobject-2.0.dll.a
lib/gobject-2.0.lib
lib/libgthread-2.0.dll.a
lib/gthread-2.0.lib
lib/glib-2.0
lib/pkgconfig/glib-2.0.pc
lib/pkgconfig/gmodule-2.0.pc
lib/pkgconfig/gobject-2.0.pc
lib/pkgconfig/gthread-2.0.pc
share/aclocal/glib-2.0.m4
share/aclocal/glib-gettext.m4
share/glib-2.0
man/man1/glib-mkenums.1
man/man1/glib-genmarshal.1
EOF
