rem cl.exe /nologo /D "_WINDOWS" /D "_MBCS" /D "NOLIBTOOL" /W3 /wd4244 /wd4267 /MD /I.. /I..\include /I.\include /D "_REENTRANT" /D "HAVE_WIN32_THREADS" /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE /D "NDEBUG" /O2 /Foint.msvc\ /c ..\buf.c ..\c14n.c ..\catalog.c ..\chvalid.c ..\debugXML.c ..\dict.c ..\DOCBparser.c ..\encoding.c ..\entities.c ..\error.c ..\globals.c ..\hash.c ..\HTMLparser.c ..\HTMLtree.c ..\legacy.c ..\list.c ..\nanoftp.c ..\nanohttp.c ..\parser.c ..\parserInternals.c ..\pattern.c ..\relaxng.c ..\SAX2.c ..\SAX.c ..\schematron.c ..\threads.c ..\tree.c ..\uri.c ..\valid.c ..\xinclude.c ..\xlink.c ..\xmlIO.c ..\xmlmemory.c ..\xmlreader.c ..\xmlregexp.c ..\xmlmodule.c ..\xmlsave.c ..\xmlschemas.c ..\xmlschemastypes.c ..\xmlunicode.c ..\xmlwriter.c ..\xpath.c ..\xpointer.c ..\xmlstring.c
rem lib.exe /nologo /out:Release_TS\php5embed.lib /nologo /version:5.6.33 /incremental:no /debug /opt:ref,icf /libpath:"C:\php-sdk\phpdev\vc9\x86\deps\lib" Release_TS\sapi\embed\php_embed.obj Release_TS\php5ts.lib   Release_TS\php5embed.lib.res
rem lib.exe /nologo /OUT:bin.msvc\libxml2_ad.lib int.a.msvc\buf.obj int.a.msvc\c14n.obj int.a.msvc\catalog.obj int.a.msvc\chvalid.obj int.a.msvc\debugXML.obj int.a.msvc\dict.obj int.a.msvc\DOCBparser.obj int.a.msvc\encoding.obj int.a.msvc\entities.obj int.a.msvc\error.obj int.a.msvc\globals.obj int.a.msvc\hash.obj int.a.msvc\HTMLparser.obj int.a.msvc\HTMLtree.obj int.a.msvc\legacy.obj int.a.msvc\list.obj int.a.msvc\nanoftp.obj int.a.msvc\nanohttp.obj int.a.msvc\parser.obj int.a.msvc\parserInternals.obj int.a.msvc\pattern.obj int.a.msvc\relaxng.obj int.a.msvc\SAX2.obj int.a.msvc\SAX.obj int.a.msvc\schematron.obj int.a.msvc\threads.obj int.a.msvc\tree.obj int.a.msvc\uri.obj int.a.msvc\valid.obj int.a.msvc\xinclude.obj int.a.msvc\xlink.obj int.a.msvc\xmlIO.obj int.a.msvc\xmlmemory.obj int.a.msvc\xmlreader.obj int.a.msvc\xmlregexp.obj int.a.msvc\xmlmodule.obj int.a.msvc\xmlsave.obj int.a.msvc\xmlschemas.obj int.a.msvc\xmlschemastypes.obj int.a.msvc\xmlunicode.obj int.a.msvc\xmlwriter.obj int.a.msvc\xpath.obj int.a.msvc\xpointer.obj int.a.msvc\xmlstring.obj
rem rc.exe /d "_DEBUG" /l 0x809 /fo".\libxml2.res" ".\libxml2.rc"
rem link.exe /nologo /VERSION:2.9 /LIBPATH:bin.msvc /LIBPATH:.\lib /DLL  /IMPLIB:bin.msvc\libxml2d.lib /OUT:bin.msvc\libxml2d.dll int.msvc\buf.obj int.msvc\c14n.obj int.msvc\catalog.obj int.msvc\chvalid.obj int.msvc\debugXML.obj int.msvc\dict.obj int.msvc\DOCBparser.obj int.msvc\encoding.obj int.msvc\entities.obj int.msvc\error.obj int.msvc\globals.obj int.msvc\hash.obj int.msvc\HTMLparser.obj int.msvc\HTMLtree.obj int.msvc\legacy.obj int.msvc\list.obj int.msvc\nanoftp.obj int.msvc\nanohttp.obj int.msvc\parser.obj int.msvc\parserInternals.obj int.msvc\pattern.obj int.msvc\relaxng.obj int.msvc\SAX2.obj int.msvc\SAX.obj int.msvc\schematron.obj int.msvc\threads.obj int.msvc\tree.obj int.msvc\uri.obj int.msvc\valid.obj int.msvc\xinclude.obj int.msvc\xlink.obj int.msvc\xmlIO.obj int.msvc\xmlmemory.obj int.msvc\xmlreader.obj int.msvc\xmlregexp.obj int.msvc\xmlmodule.obj int.msvc\xmlsave.obj int.msvc\xmlschemas.obj int.msvc\xmlschemastypes.obj int.msvc\xmlunicode.obj int.msvc\xmlwriter.obj int.msvc\xpath.obj int.msvc\xpointer.obj int.msvc\xmlstring.obj  wsock32.lib ws2_32.lib kernel32.lib libxml2.res
link.exe /nologo /VERSION:2.9 /LIBPATH:bin.msvc /LIBPATH:.\lib /DLL /DEBUG /IMPLIB:bin.msvc\libxml2.lib /OUT:bin.msvc\libxml2.dll int.msvc\buf.obj int.msvc\c14n.obj int.msvc\catalog.obj int.msvc\chvalid.obj int.msvc\debugXML.obj int.msvc\dict.obj int.msvc\DOCBparser.obj int.msvc\encoding.obj int.msvc\entities.obj int.msvc\error.obj int.msvc\globals.obj int.msvc\hash.obj int.msvc\HTMLparser.obj int.msvc\HTMLtree.obj int.msvc\legacy.obj int.msvc\list.obj int.msvc\nanoftp.obj int.msvc\nanohttp.obj int.msvc\parser.obj int.msvc\parserInternals.obj int.msvc\pattern.obj int.msvc\relaxng.obj int.msvc\SAX2.obj int.msvc\SAX.obj int.msvc\schematron.obj int.msvc\threads.obj int.msvc\tree.obj int.msvc\uri.obj int.msvc\valid.obj int.msvc\xinclude.obj int.msvc\xlink.obj int.msvc\xmlIO.obj int.msvc\xmlmemory.obj int.msvc\xmlreader.obj int.msvc\xmlregexp.obj int.msvc\xmlmodule.obj int.msvc\xmlsave.obj int.msvc\xmlschemas.obj int.msvc\xmlschemastypes.obj int.msvc\xmlunicode.obj int.msvc\xmlwriter.obj int.msvc\xpath.obj int.msvc\xpointer.obj int.msvc\xmlstring.obj  wsock32.lib ws2_32.lib kernel32.lib libxml2.res /PDB:"bin.msvc\libXML2_a_dll.PDB"

lib.exe /nologo /OUT:bin.msvc\libXML2_a_DLL.lib int.a.dll.msvc\buf.obj int.a.dll.msvc\c14n.obj int.a.dll.msvc\catalog.obj int.a.dll.msvc\chvalid.obj int.a.dll.msvc\debugXML.obj int.a.dll.msvc\dict.obj int.a.dll.msvc\DOCBparser.obj int.a.dll.msvc\encoding.obj int.a.dll.msvc\entities.obj int.a.dll.msvc\error.obj int.a.dll.msvc\globals.obj int.a.dll.msvc\hash.obj int.a.dll.msvc\HTMLparser.obj int.a.dll.msvc\HTMLtree.obj int.a.dll.msvc\legacy.obj int.a.dll.msvc\list.obj int.a.dll.msvc\nanoftp.obj int.a.dll.msvc\nanohttp.obj int.a.dll.msvc\parser.obj int.a.dll.msvc\parserInternals.obj int.a.dll.msvc\pattern.obj int.a.dll.msvc\relaxng.obj int.a.dll.msvc\SAX2.obj int.a.dll.msvc\SAX.obj int.a.dll.msvc\schematron.obj int.a.dll.msvc\threads.obj int.a.dll.msvc\tree.obj int.a.dll.msvc\uri.obj int.a.dll.msvc\valid.obj int.a.dll.msvc\xinclude.obj int.a.dll.msvc\xlink.obj int.a.dll.msvc\xmlIO.obj int.a.dll.msvc\xmlmemory.obj int.a.dll.msvc\xmlreader.obj int.a.dll.msvc\xmlregexp.obj int.a.dll.msvc\xmlmodule.obj int.a.dll.msvc\xmlsave.obj int.a.dll.msvc\xmlschemas.obj int.a.dll.msvc\xmlschemastypes.obj int.a.dll.msvc\xmlunicode.obj int.a.dll.msvc\xmlwriter.obj int.a.dll.msvc\xpath.obj int.a.dll.msvc\xpointer.obj int.a.dll.msvc\xmlstring.obj 

rem cl.exe /nologo /D "_WINDOWS" /D "_MBCS" /D "NOLIBTOOL" /W3 /wd4244 /wd4267 /MD /I.. /I..\include /I.\include /D "_REENTRANT" /D "HAVE_WIN32_THREADS" /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE /D "NDEBUG" /O2 /Foint.utils.msvc\ /c ..\xmllint.c
rem link.exe /nologo /VERSION:2.9 /LIBPATH:bin.msvc /LIBPATH:.\lib /OUT:bin.msvc\xmllint.exe libxml2d.lib  wsock32.lib ws2_32.lib kernel32.lib int.utils.msvc\xmllint.obj

rem cl.exe /EP /nologo /I..\include /D "NOLIBTOOL" /D "_REENTRANT" libxml2.def.src > int.msvc\libxml2.def
cl.exe /nologo /D "_WINDOWS" /D "_MBCS" /D "NOLIBTOOL" /W3 /wd4244 /wd4267 /MD /I.. /I..\include /I.\include /D "_REENTRANT" /D "HAVE_WIN32_THREADS" /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE /D "NDEBUG" /O2 /Foint.msvc\ /c ..\buf.c ..\c14n.c ..\catalog.c ..\chvalid.c ..\debugXML.c ..\dict.c ..\DOCBparser.c ..\encoding.c ..\entities.c ..\error.c ..\globals.c ..\hash.c ..\HTMLparser.c ..\HTMLtree.c ..\legacy.c ..\list.c ..\nanoftp.c ..\nanohttp.c ..\parser.c ..\parserInternals.c ..\pattern.c ..\relaxng.c ..\SAX2.c ..\SAX.c ..\schematron.c ..\threads.c ..\tree.c ..\uri.c ..\valid.c ..\xinclude.c ..\xlink.c ..\xmlIO.c ..\xmlmemory.c ..\xmlreader.c ..\xmlregexp.c ..\xmlmodule.c ..\xmlsave.c ..\xmlschemas.c ..\xmlschemastypes.c ..\xmlunicode.c ..\xmlwriter.c ..\xpath.c ..\xpointer.c ..\xmlstring.c libxml2.res 

