#define yy_create_buffer plpgsql_base_yy_create_buffer
#define yy_delete_buffer plpgsql_base_yy_delete_buffer
#define yy_scan_buffer plpgsql_base_yy_scan_buffer
#define yy_scan_string plpgsql_base_yy_scan_string
#define yy_scan_bytes plpgsql_base_yy_scan_bytes
#define yy_flex_debug plpgsql_base_yy_flex_debug
#define yy_init_buffer plpgsql_base_yy_init_buffer
#define yy_flush_buffer plpgsql_base_yy_flush_buffer
#define yy_load_buffer_state plpgsql_base_yy_load_buffer_state
#define yy_switch_to_buffer plpgsql_base_yy_switch_to_buffer
#define yyin plpgsql_base_yyin
#define yyleng plpgsql_base_yyleng
#define yylex plpgsql_base_yylex
#define yyout plpgsql_base_yyout
#define yyrestart plpgsql_base_yyrestart
#define yytext plpgsql_base_yytext
#define yylineno plpgsql_base_yylineno
#define yywrap plpgsql_base_yywrap

#line 21 "pl_scan.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 * $FreeBSD: src/usr.bin/lex/flex.skl,v 1.4 1999/10/27 07:56:44 obrien Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
static yyconst short int yy_acclist[330] =
    {   0,
       71,   71,   74,   72,   73,   61,   72,   73,   61,   73,
       48,   72,   73,   72,   73,   67,   72,   73,   72,   73,
       72,   73,   72,   73,   60,   72,   73,   72,   73,    2,
       72,   73,   48,   72,   73,   48,   72,   73,   48,   72,
       73,   48,   72,   73,   48,   72,   73,   48,   72,   73,
       48,   72,   73,   48,   72,   73,   48,   72,   73,   48,
       72,   73,   48,   72,   73,   48,   72,   73,   48,   72,
       73,   48,   72,   73,   48,   72,   73,   48,   72,   73,
       72,   73,   71,   73,   70,   73,   73,   66,   73,   65,
       73,   66,   73,   61,   48,   54,   62,    3,   63,   60,

        1,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   23,   48,   24,   48,
       26,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   42,   48,   48,   48,   71,   69,   68,   64,
       49,   62,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   15,   48,   48,   48,   48,   48,   20,
       48,   48,   22,   48,   48,   48,   28,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   49,   55,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   47,   48,   13,   48,   48,   48,

       48,   18,   48,   48,   21,   48,   25,   48,   27,   48,
       48,   30,   48,   31,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   41,   48,   43,   48,   44,   48,
       48,   50,   55,    4,   48,    5,   48,    6,   48,   48,
       48,    9,   48,   48,   48,   48,   14,   48,   48,   48,
       19,   48,   48,   48,   33,   48,   48,   48,   48,   48,
       48,   48,   48,   45,   48,   51,   50,   56,   48,    8,
       48,   48,   48,   48,   48,   48,   29,   48,   48,   34,
       48,   35,   48,   48,   37,   48,   48,   48,   40,   48,
       57,   56,   48,   10,   48,   11,   48,   48,   48,   17,

       48,   32,   48,   48,   38,   48,   48,   46,   52,    7,
       48,   48,   48,   48,   48,   53,   58,   48,   16,   48,
       48,   39,   48,   59,   48,   36,   48,   12,   48
    } ;

static yyconst short int yy_accept[275] =
    {   0,
        1,    1,    1,    2,    3,    3,    3,    4,    6,    9,
       11,   14,   16,   19,   21,   23,   25,   28,   30,   33,
       36,   39,   42,   45,   48,   51,   54,   57,   60,   63,
       66,   69,   72,   75,   78,   81,   83,   85,   87,   88,
       90,   92,   94,   95,   96,   96,   96,   97,   98,   99,
      100,  101,  102,  103,  104,  105,  106,  107,  108,  109,
      110,  111,  112,  113,  114,  115,  116,  117,  119,  121,
      123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
      133,  135,  136,  137,  137,  138,  139,  140,  141,  141,
      141,  142,  142,  142,  143,  144,  145,  146,  147,  148,

      149,  150,  151,  152,  153,  154,  156,  157,  158,  159,
      160,  162,  163,  165,  166,  167,  169,  170,  171,  172,
      173,  174,  175,  176,  177,  178,  179,  180,  181,  182,
      183,  184,  184,  184,  184,  185,  185,  185,  185,  185,
      186,  187,  188,  189,  190,  191,  192,  193,  194,  195,
      197,  199,  200,  201,  202,  204,  205,  207,  209,  211,
      212,  214,  216,  217,  218,  219,  220,  221,  222,  223,
      224,  225,  227,  229,  231,  232,  232,  232,  232,  232,
      233,  233,  233,  234,  234,  234,  236,  238,  240,  241,
      242,  244,  245,  246,  247,  249,  250,  251,  253,  254,

      255,  257,  258,  259,  260,  261,  262,  263,  264,  266,
      266,  266,  267,  267,  268,  268,  268,  268,  269,  270,
      272,  273,  274,  275,  276,  277,  279,  280,  282,  284,
      285,  287,  288,  289,  291,  291,  291,  291,  291,  292,
      292,  293,  294,  296,  298,  299,  300,  302,  304,  305,
      307,  308,  309,  309,  310,  310,  310,  312,  313,  314,
      315,  316,  317,  317,  318,  319,  321,  322,  324,  325,
      326,  328,  330,  330
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    8,    1,    9,    1,
        1,   10,    1,    1,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    1,    1,
       16,    1,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,    5,    5,   28,   29,   30,   31,   32,
        5,   33,   34,   35,   36,   37,   38,   39,   40,    5,
        1,   17,    1,    1,   18,    1,   19,   20,   21,   22,

       23,   24,   25,   26,   27,    5,    5,   28,   29,   30,
       31,   32,    5,   33,   34,   35,   36,   37,   38,   39,
       40,    5,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5
    } ;

static yyconst int yy_meta[41] =
    {   0,
        1,    1,    2,    3,    4,    1,    1,    5,    6,    1,
        1,    5,    1,    7,    1,    1,    6,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4
    } ;

static yyconst short int yy_base[288] =
    {   0,
        0,  466,   32,   33,   41,   42,  469,  736,   44,   51,
       48,  439,  736,  432,  416,  408,  397,  388,  736,   49,
       50,   51,   57,   58,   73,   60,   83,   59,   90,   91,
       66,   93,  102,  103,  110,  368,    0,  388,    0,  736,
      736,  367,  128,  125,   59,    0,  127,    0,  736,  736,
      358,  736,  130,  136,  137,  139,  138,  146,  144,  147,
      152,  165,  167,  166,  172,  173,  181,  183,  184,  190,
      191,  198,  199,  200,  201,  209,  229,  206,  212,  220,
      217,  223,  230,  338,    0,  736,  736,  736,  314,  293,
      218,  212,    0,    0,  246,  240,  248,  260,  261,  262,

      263,  268,  271,  269,  276,  277,  285,  292,  294,  297,
      278,  299,  302,  304,  307,  309,  312,  314,  319,  322,
      329,  330,  338,  339,  340,  346,  345,  347,  353,  354,
      359,  297,  287,  291,  361,  257,    0,  247,  222,  370,
      371,  373,  378,  380,  381,  383,  388,  386,  394,  401,
      402,  408,  409,  411,  417,  418,  419,  425,  426,  427,
      428,  434,  437,  442,  443,  444,  449,  450,  451,  458,
      459,  452,  466,  473,  474,  234,  216,  226,  206,    0,
      201,  183,  479,  165,    0,  480,  481,  482,  487,  488,
      490,  493,  495,  496,  501,  502,  503,  504,  510,  512,

      517,  520,  523,  522,  528,  531,  536,  539,  541,  166,
      143,  736,  150,    0,  137,  142,  122,    0,  542,  544,
      547,  552,  554,  563,  561,  568,  569,  570,  571,  577,
      584,  585,  591,  592,  123,  108,  105,   87,  736,   88,
        0,  593,  594,  599,  601,  602,  604,  607,  609,  610,
      612,  736,   96,  736,   77,   85,  617,  618,  623,  629,
      626,  736,   77,  736,  631,  636,  638,  639,  736,  646,
      647,  654,  736,  680,  687,  691,  698,  705,   72,  712,
      716,   71,   60,  720,  724,   39,  728
    } ;

static yyconst short int yy_def[288] =
    {   0,
      273,    1,  274,  274,  275,  275,  273,  273,  273,  273,
      276,  273,  273,  273,  273,  273,  273,  273,  273,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  273,  277,  273,  278,  273,
      273,  273,  273,  276,  273,  279,  273,  280,  273,  273,
      273,  273,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  273,  277,  273,  273,  273,  273,  273,
      281,  273,  282,  280,  276,  276,  276,  276,  276,  276,

      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  273,  273,  273,  281,  273,  283,  273,  273,  284,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  273,  273,  273,  273,  285,
      273,  273,  284,  273,  286,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,

      276,  276,  276,  276,  276,  276,  276,  276,  276,  273,
      273,  273,  273,  285,  273,  273,  273,  287,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  273,  273,  273,  273,  273,  273,
      287,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  273,  273,  273,  273,  273,  276,  276,  276,  276,
      276,  273,  273,  273,  276,  276,  276,  276,  273,  276,
      276,  276,    0,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273
    } ;

static yyconst short int yy_nxt[777] =
    {   0,
        8,    9,   10,    9,   11,    8,   12,    8,   13,    8,
       14,   15,   16,   17,   18,   19,    8,   11,   20,   21,
       22,   23,   24,   25,   26,   11,   27,   28,   11,   29,
       30,   31,   32,   33,   34,   11,   11,   35,   11,   11,
       38,   38,  218,   41,   41,   43,   43,   43,   39,   39,
       42,   42,   43,   43,   43,   45,   45,   45,   45,   46,
       46,   46,   46,  180,   45,   45,   45,   45,   46,   46,
       46,   46,   54,   45,  140,   91,   53,   46,   55,   58,
       45,   56,   67,   59,   46,   61,   57,   62,   75,   71,
       45,   89,   60,   90,   46,   64,   63,   45,   45,  269,

       45,   46,   46,   65,   46,   66,   68,  264,  263,   45,
       45,   76,   69,   46,   46,   77,   70,   45,  262,  256,
       72,   46,   74,   78,   79,   73,  255,  254,   80,   43,
       43,   43,   45,   81,   92,   83,   46,   45,   93,  253,
       47,   46,   82,   45,   45,   45,   45,   46,   46,   46,
       46,   45,  252,   45,   45,   46,   95,   46,   46,   45,
       96,  240,  103,   46,  239,  100,  101,   97,   98,  102,
       99,  238,   45,   45,   45,  104,   46,   46,   46,   45,
       45,  237,  236,   46,   46,  105,  106,  107,   45,  108,
       45,   45,   46,  109,   46,   46,  235,   45,   45,  217,

      110,   46,   46,  112,  111,   45,   45,   45,   45,   46,
       46,   46,   46,   45,  216,  113,   45,   46,  114,   45,
       46,  115,  118,   46,   45,  136,  117,   45,   46,  137,
       45,   46,  116,  119,   46,  120,   45,   45,  215,  127,
       46,   46,  128,  126,  138,  213,  139,   45,  212,  121,
      211,   46,  130,   45,  129,   45,  131,   46,  122,   46,
      210,  182,  123,  124,  141,  125,  142,   45,   45,   45,
       45,   46,   46,   46,   46,   45,   45,  181,   45,   46,
       46,  143,   46,   45,   45,   45,  148,   46,   46,   46,
      147,  179,   45,  144,  145,  149,   46,  146,  151,   45,

      150,   45,  152,   46,   45,   46,   45,  153,   46,   45,
       46,   45,  154,   46,   45,   46,   45,  156,   46,   45,
       46,   45,  178,   46,  177,   46,   45,  157,  155,   45,
       46,  176,  134,   46,  158,  160,   45,   45,  159,  161,
       46,   46,  163,  162,  133,   45,   45,   45,  166,   46,
       46,   46,   45,   45,   45,  164,   46,   46,   46,  165,
       45,   45,  169,  170,   46,   46,   45,  171,  136,  132,
       46,   51,  137,  167,  168,  173,  172,  184,   45,   88,
       45,  185,   46,  174,   46,   45,  175,   45,   45,   46,
       45,   46,   46,   45,   46,   45,   86,   46,   84,   46,

      188,   45,  187,   52,  186,   46,  192,  191,   45,   45,
       51,  190,   46,   46,  189,   45,   45,   50,   45,   46,
       46,  193,   46,  194,   45,   45,   45,   49,   46,   46,
       46,  195,   45,   45,   45,   45,   46,   46,   46,   46,
      196,   45,   48,  198,   45,   46,  197,  199,   46,   45,
       45,   45,   47,   46,   46,   46,   45,   45,   45,   45,
       46,   46,   46,   46,  201,   45,   45,  200,  273,   46,
       46,   36,  203,   45,  273,  202,  204,   46,  207,  208,
       45,   45,  205,  206,   46,   46,  184,   45,   45,   45,
      185,   46,   46,   46,   45,   45,  209,   45,   46,   46,

       45,   46,   45,   45,   46,  219,   46,   46,   45,   45,
       45,   45,   46,   46,   46,   46,  273,   45,  273,   45,
      220,   46,  222,   46,   45,  221,  223,   45,   46,   45,
       45,   46,  226,   46,   46,   45,  224,  225,   45,   46,
      273,  228,   46,   45,  227,  229,   45,   46,   45,   45,
       46,   45,   46,   46,   45,   46,  230,  231,   46,   45,
      273,   45,  273,   46,  232,   46,  233,  273,   45,  243,
       45,  242,   46,  234,   46,   45,   45,   45,   45,   46,
       46,   46,   46,  247,   45,  273,  244,  245,   46,  246,
      273,   45,   45,  273,  249,   46,   46,  248,   45,   45,

       45,   45,   46,   46,   46,   46,   45,  250,   45,   45,
       46,   45,   46,   46,   45,   46,   45,   45,   46,   45,
       46,   46,  273,   46,   45,   45,  251,  257,   46,   46,
       45,  273,  259,   45,   46,  258,   45,   46,   45,  260,
       46,  261,   46,   45,  265,   45,   45,   46,  273,   46,
       46,  270,  266,   45,   45,  267,  273,   46,   46,  271,
      268,   45,  273,  273,  273,   46,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  272,
       37,   37,   37,   37,   37,   37,   37,   40,   40,   40,
       40,   40,   40,   40,   44,   44,  273,   44,   85,   85,

       85,   85,   85,  273,   85,   87,  273,   87,   87,   87,
       87,   87,   94,  273,  273,   94,   94,   94,   94,  135,
      135,  273,  135,  183,  183,  273,  183,  214,  273,  273,
      214,  241,  273,  273,  241,    7,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273
    } ;

static yyconst short int yy_chk[777] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,  286,    5,    6,    9,    9,    9,    3,    4,
        5,    6,   10,   10,   10,   11,   20,   21,   22,   11,
       20,   21,   22,  283,   23,   24,   28,   26,   23,   24,
       28,   26,   21,   31,  282,  279,   20,   31,   22,   23,
       25,   22,   26,   23,   25,   24,   22,   24,   31,   28,
       27,   45,   23,   45,   27,   25,   24,   29,   30,  263,

       32,   29,   30,   25,   32,   25,   27,  256,  255,   33,
       34,   32,   27,   33,   34,   32,   27,   35,  253,  240,
       29,   35,   30,   32,   33,   29,  238,  237,   34,   43,
       43,   43,   44,   34,   47,   35,   44,   53,   47,  236,
       47,   53,   34,   54,   55,   57,   56,   54,   55,   57,
       56,   59,  235,   58,   60,   59,   53,   58,   60,   61,
       54,  217,   59,   61,  216,   58,   58,   55,   56,   58,
       57,  215,   62,   64,   63,   60,   62,   64,   63,   65,
       66,  213,  211,   65,   66,   61,   62,   63,   67,   63,
       68,   69,   67,   63,   68,   69,  210,   70,   71,  184,

       64,   70,   71,   66,   65,   72,   73,   74,   75,   72,
       73,   74,   75,   78,  182,   67,   76,   78,   69,   79,
       76,   71,   74,   79,   81,   91,   73,   80,   81,   91,
       82,   80,   72,   75,   82,   76,   77,   83,  181,   79,
       77,   83,   80,   78,   92,  179,   92,   96,  178,   77,
      177,   96,   83,   95,   82,   97,   83,   95,   77,   97,
      176,  139,   77,   77,   95,   77,   96,   98,   99,  100,
      101,   98,   99,  100,  101,  102,  104,  138,  103,  102,
      104,   97,  103,  105,  106,  111,  102,  105,  106,  111,
      101,  136,  107,   98,   99,  103,  107,  100,  105,  108,

      104,  109,  105,  108,  110,  109,  112,  107,  110,  113,
      112,  114,  108,  113,  115,  114,  116,  110,  115,  117,
      116,  118,  134,  117,  133,  118,  119,  112,  109,  120,
      119,  132,   90,  120,  114,  116,  121,  122,  115,  117,
      121,  122,  119,  118,   89,  123,  124,  125,  122,  123,
      124,  125,  127,  126,  128,  120,  127,  126,  128,  121,
      129,  130,  125,  126,  129,  130,  131,  127,  135,   84,
      131,   51,  135,  123,  124,  129,  128,  140,  141,   42,
      142,  140,  141,  130,  142,  143,  131,  144,  145,  143,
      146,  144,  145,  148,  146,  147,   38,  148,   36,  147,

      143,  149,  142,   18,  141,  149,  147,  146,  150,  151,
       17,  145,  150,  151,  144,  152,  153,   16,  154,  152,
      153,  148,  154,  149,  155,  156,  157,   15,  155,  156,
      157,  152,  158,  159,  160,  161,  158,  159,  160,  161,
      153,  162,   14,  156,  163,  162,  154,  160,  163,  164,
      165,  166,   12,  164,  165,  166,  167,  168,  169,  172,
      167,  168,  169,  172,  164,  170,  171,  163,    7,  170,
      171,    2,  166,  173,    0,  165,  167,  173,  170,  171,
      174,  175,  168,  169,  174,  175,  183,  186,  187,  188,
      183,  186,  187,  188,  189,  190,  175,  191,  189,  190,

      192,  191,  193,  194,  192,  189,  193,  194,  195,  196,
      197,  198,  195,  196,  197,  198,    0,  199,    0,  200,
      190,  199,  193,  200,  201,  192,  194,  202,  201,  204,
      203,  202,  199,  204,  203,  205,  196,  197,  206,  205,
        0,  202,  206,  207,  200,  203,  208,  207,  209,  219,
      208,  220,  209,  219,  221,  220,  204,  205,  221,  222,
        0,  223,    0,  222,  206,  223,  207,    0,  225,  221,
      224,  219,  225,  208,  224,  226,  227,  228,  229,  226,
      227,  228,  229,  225,  230,    0,  222,  223,  230,  224,
        0,  231,  232,    0,  230,  231,  232,  227,  233,  234,

      242,  243,  233,  234,  242,  243,  244,  232,  245,  246,
      244,  247,  245,  246,  248,  247,  249,  250,  248,  251,
      249,  250,    0,  251,  257,  258,  233,  242,  257,  258,
      259,    0,  246,  261,  259,  245,  260,  261,  265,  249,
      260,  251,  265,  266,  258,  267,  268,  266,    0,  267,
      268,  265,  259,  270,  271,  260,    0,  270,  271,  267,
      261,  272,    0,    0,    0,  272,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  270,
      274,  274,  274,  274,  274,  274,  274,  275,  275,  275,
      275,  275,  275,  275,  276,  276,    0,  276,  277,  277,

      277,  277,  277,    0,  277,  278,    0,  278,  278,  278,
      278,  278,  280,    0,    0,  280,  280,  280,  280,  281,
      281,    0,  281,  284,  284,    0,  284,  285,    0,    0,
      285,  287,    0,    0,  287,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scan.l"
#define INITIAL 0
#line 2 "scan.l"
/**********************************************************************
 * scan.l		- Scanner for the PL/pgSQL
 *			  procedural language
 *
 * IDENTIFICATION
 *    $Header: /cvsroot/pgsql-server/src/pl/plpgsql/src/scan.l,v 1.16 2001/10/09 15:59:56 tgl Exp $
 *
 *    This software is copyrighted by Jan Wieck - Hamburg.
 *
 *    The author hereby grants permission  to  use,  copy,  modify,
 *    distribute,  and  license this software and its documentation
 *    for any purpose, provided that existing copyright notices are
 *    retained  in  all  copies  and  that  this notice is included
 *    verbatim in any distributions. No written agreement, license,
 *    or  royalty  fee  is required for any of the authorized uses.
 *    Modifications to this software may be  copyrighted  by  their
 *    author  and  need  not  follow  the licensing terms described
 *    here, provided that the new terms are  clearly  indicated  on
 *    the first page of each file where they apply.
 *
 *    IN NO EVENT SHALL THE AUTHOR OR DISTRIBUTORS BE LIABLE TO ANY
 *    PARTY  FOR  DIRECT,   INDIRECT,   SPECIAL,   INCIDENTAL,   OR
 *    CONSEQUENTIAL   DAMAGES  ARISING  OUT  OF  THE  USE  OF  THIS
 *    SOFTWARE, ITS DOCUMENTATION, OR ANY DERIVATIVES THEREOF, EVEN
 *    IF  THE  AUTHOR  HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH
 *    DAMAGE.
 *
 *    THE  AUTHOR  AND  DISTRIBUTORS  SPECIFICALLY   DISCLAIM   ANY
 *    WARRANTIES,  INCLUDING,  BUT  NOT  LIMITED  TO,  THE  IMPLIED
 *    WARRANTIES  OF  MERCHANTABILITY,  FITNESS  FOR  A  PARTICULAR
 *    PURPOSE,  AND NON-INFRINGEMENT.  THIS SOFTWARE IS PROVIDED ON
 *    AN "AS IS" BASIS, AND THE AUTHOR  AND  DISTRIBUTORS  HAVE  NO
 *    OBLIGATION   TO   PROVIDE   MAINTENANCE,   SUPPORT,  UPDATES,
 *    ENHANCEMENTS, OR MODIFICATIONS.
 *
 **********************************************************************/

#include "plpgsql.h"
#include "pl.tab.h"


static char	*plpgsql_source;
static int	plpgsql_bytes_left;
static int	scanner_functype;
static int	scanner_typereported;
static int	pushback_token;
static bool have_pushback_token;

int	plpgsql_SpaceScanned = 0;

static void plpgsql_input(char *buf, int *result, int max);

#define YY_INPUT(buf,res,max)	plpgsql_input(buf, &res, max)
#define YY_NO_UNPUT
#define IN_STRING 1
#define IN_COMMENT 2

#line 752 "pl_scan.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 66 "scan.l"

    /* ----------
     * Local variable in scanner to remember where
     * a string or comment started
     * ----------
     */
    int	start_lineno = 0;

    /* ----------
     * Reset the state when entering the scanner
     * ----------
     */
    BEGIN INITIAL;
    plpgsql_SpaceScanned = 0;

    /* ----------
     * On the first call to a new source report the
     * functions type (T_FUNCTION or T_TRIGGER)
     * ----------
     */
	if (!scanner_typereported)
	{
		scanner_typereported = 1;
		return scanner_functype;
	}

    /* ----------
     * The keyword rules
     * ----------
     */
#line 937 "pl_scan.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yy_c_buf_p - yytext_ptr;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 274 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 736 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 96 "scan.l"
{ return K_ASSIGN;			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 97 "scan.l"
{ return K_ASSIGN;			}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 98 "scan.l"
{ return K_DOTDOT;			}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 99 "scan.l"
{ return K_ALIAS;			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 100 "scan.l"
{ return K_BEGIN;			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 101 "scan.l"
{ return K_CLOSE;			}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 102 "scan.l"
{ return K_CONSTANT;		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 103 "scan.l"
{ return K_CURSOR;			}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 104 "scan.l"
{ return K_DEBUG;			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 105 "scan.l"
{ return K_DECLARE;			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 106 "scan.l"
{ return K_DEFAULT;			}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 107 "scan.l"
{ return K_DIAGNOSTICS;		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 108 "scan.l"
{ return K_ELSE;			}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 109 "scan.l"
{ return K_ELSIF;           }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 110 "scan.l"
{ return K_END;				}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 111 "scan.l"
{ return K_EXCEPTION;		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 112 "scan.l"
{ return K_EXECUTE;			}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 113 "scan.l"
{ return K_EXIT;			}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 114 "scan.l"
{ return K_FETCH;			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 115 "scan.l"
{ return K_FOR;				}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 116 "scan.l"
{ return K_FROM;			}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 117 "scan.l"
{ return K_GET;				}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 118 "scan.l"
{ return K_IF;				}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 119 "scan.l"
{ return K_IN;				}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 120 "scan.l"
{ return K_INTO;			}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 121 "scan.l"
{ return K_IS;				}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 122 "scan.l"
{ return K_LOOP;			}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 123 "scan.l"
{ return K_NOT;				}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 124 "scan.l"
{ return K_NOTICE;			}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 125 "scan.l"
{ return K_NULL;			}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 126 "scan.l"
{ return K_OPEN;			}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 127 "scan.l"
{ return K_PERFORM;			}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 128 "scan.l"
{ return K_RAISE;			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 129 "scan.l"
{ return K_RECORD;			}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 130 "scan.l"
{ return K_RENAME;			}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 131 "scan.l"
{ return K_RESULT_OID;		}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 132 "scan.l"
{ return K_RETURN;			}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 133 "scan.l"
{ return K_REVERSE;			}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 134 "scan.l"
{ return K_ROW_COUNT;		}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 135 "scan.l"
{ return K_SELECT;			}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 136 "scan.l"
{ return K_THEN;			}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 137 "scan.l"
{ return K_TO;				}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 138 "scan.l"
{ return K_TYPE;			}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 139 "scan.l"
{ return K_WHEN;			}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 140 "scan.l"
{ return K_WHILE;			}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 142 "scan.l"
{ return O_OPTION;			}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 143 "scan.l"
{ return O_DUMP;			}
	YY_BREAK
/* ----------
     * Special word rules
     * ----------
     */
case 48:
YY_RULE_SETUP
#line 150 "scan.l"
{ return plpgsql_parse_word(yytext);	}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 151 "scan.l"
{ return plpgsql_parse_dblword(yytext);	}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 152 "scan.l"
{ return plpgsql_parse_tripword(yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 153 "scan.l"
{ return plpgsql_parse_wordtype(yytext);	}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 154 "scan.l"
{ return plpgsql_parse_dblwordtype(yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 155 "scan.l"
{ return plpgsql_parse_wordrowtype(yytext);	}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 157 "scan.l"
{ return plpgsql_parse_word(yytext);	}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 158 "scan.l"
{ return plpgsql_parse_dblword(yytext);	}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 159 "scan.l"
{ return plpgsql_parse_tripword(yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 160 "scan.l"
{ return plpgsql_parse_wordtype(yytext);	}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 161 "scan.l"
{ return plpgsql_parse_dblwordtype(yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 162 "scan.l"
{ return plpgsql_parse_wordrowtype(yytext);	}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 164 "scan.l"
{ return T_NUMBER;			}
	YY_BREAK
/* ----------
     * Ignore whitespaces but remember this happened
     * ----------
     */
case 61:
YY_RULE_SETUP
#line 170 "scan.l"
{ plpgsql_SpaceScanned = 1;		}
	YY_BREAK
/* ----------
     * Eat up comments
     * ----------
     */
case 62:
YY_RULE_SETUP
#line 176 "scan.l"
;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 177 "scan.l"
{ start_lineno = yylineno;
			  BEGIN IN_COMMENT;
			}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 180 "scan.l"
{ BEGIN INITIAL;			}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 181 "scan.l"
;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 182 "scan.l"
;
	YY_BREAK
case YY_STATE_EOF(IN_COMMENT):
#line 183 "scan.l"
{
				plpgsql_error_lineno = start_lineno;
				elog(ERROR, "unterminated comment");
			}
	YY_BREAK
/* ----------
     * Collect anything inside of ''s and return one STRING
     * ----------
     */
case 67:
YY_RULE_SETUP
#line 192 "scan.l"
{ start_lineno = yylineno;
			  BEGIN IN_STRING;
			  yymore();
			}
	YY_BREAK
case 68:
#line 197 "scan.l"
case 69:
YY_RULE_SETUP
#line 197 "scan.l"
{ yymore();				}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 198 "scan.l"
{ BEGIN INITIAL;
			  return T_STRING;
			}
	YY_BREAK
case YY_STATE_EOF(IN_STRING):
#line 201 "scan.l"
{
				plpgsql_error_lineno = start_lineno;
				elog(ERROR, "unterminated string");
			}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 205 "scan.l"
{ yymore();				}
	YY_BREAK
/* ----------
     * Any unmatched character is returned as is
     * ----------
     */
case 72:
YY_RULE_SETUP
#line 211 "scan.l"
{ return yytext[0];			}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 213 "scan.l"
ECHO;
	YY_BREAK
#line 1438 "pl_scan.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 274 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 274 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 273);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 213 "scan.l"


int
yywrap()
{
    return 1;
}


static void
plpgsql_input(char *buf, int *result, int max)
{
    int		n = max;

    if (n > plpgsql_bytes_left)
        n = plpgsql_bytes_left;

    if (n == 0)
	{
        *result = YY_NULL;
		return;
    }

    *result = n;
    memcpy(buf, plpgsql_source, n);
    plpgsql_source += n;
    plpgsql_bytes_left -= n;
}

/*
 * This is the yylex routine called from outside.  It exists to provide
 * a token pushback facility.
 */
int
plpgsql_yylex(void)
{
	if (have_pushback_token)
	{
		have_pushback_token = false;
		return pushback_token;
	}
	return yylex();
}

/*
 * Push back a single token to be re-read by next plpgsql_yylex() call.
 */
void
plpgsql_push_back_token(int token)
{
	if (have_pushback_token)
		elog(ERROR, "plpgsql_push_back_token: can't push back multiple tokens");
	pushback_token = token;
	have_pushback_token = true;
}


/*
 * Initialize the scanner for new input.
 */
void
plpgsql_setinput(char *source, int functype)
{
    yyrestart(NULL);
    yylineno = 1;

    plpgsql_source = source;

	/*----------
	 * Hack: skip any initial newline, so that in the common coding layout
	 *		CREATE FUNCTION ... AS '
	 *			code body
	 *		' LANGUAGE 'plpgsql';
	 * we will think "line 1" is what the programmer thinks of as line 1.
	 *----------
	 */
    if (*plpgsql_source == '\r')
        plpgsql_source++;
    if (*plpgsql_source == '\n')
        plpgsql_source++;

    plpgsql_bytes_left = strlen(plpgsql_source);

    scanner_functype     = functype;
    scanner_typereported = 0;

	have_pushback_token = false;
}
